export enum MobileRoute {
  COLLECT_FEE = "COLLECT_FEE",
  MARK_ATTENDANCE = "MARK_ATTENDANCE",
  ADD_STUDENT = "ADD_STUDENT",
  ISSUE_CHALLAN = "ISSUE_CHALLAN",
  VIEW_DEFAULTERS = "VIEW_DEFAULTERS",
}
